import "@/app/globals.css" 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
